# Data Manipulation Studio

For this studio, we will revisit the data set from our last studio. If you recall, California farmers were looking for advice on growing pumpkins. We will use the same [pumpkins dataset](https://www.kaggle.com/usda/a-year-of-pumpkin-prices) as provided by the U.S. Department of Agriculture. You may have to clean data in the process of data manipulation, so feel free to pull up your notebook from the last class's studio.

We will now be focusing our attention on a different region in the United States, the Northeast. When you open up the `dataset` folder, you will have 13 CSVs, including the San Francisco and Los Angeles data from the last lesson. The 13 CSVs are each a different terminal market in the United States.

A **terminal market** is a central site, often in a metropolitan area, that serves as an assembly and trading place for commodities. Terminal markets for agricultural commodities are usually at or near major transportation hubs. [Definition Source](https://en.wikipedia.org/wiki/Terminal_market#:~:text=A%20terminal%20market%20is%20a,or%20near%20major%20transportation%20hubs)

## Getting Started

Import the CSVs for each of the following cities: Baltimore, Boston, New York, and Philadelphia. Set up a dataframe for each city.

In [41]:
# Import the necessary libraries and CSVs. Make some dataframes!

import pandas as pd

baltimore = pd.read_csv("dataset/baltimore_9-24-2016_9-30-2017.csv")
boston = pd.read_csv("dataset/boston_9-24-2016_9-30-2017.csv")
new_york = pd.read_csv("dataset/new-york_9-24-2016_9-30-2017.csv")
philadelphia = pd.read_csv("dataset/philadelphia_9-24-2016_9-30-2017.csv")

In [45]:
baltimore.head()

,Commodity Name,City Name,Type,Package,Variety,Sub Variety,Grade,Date,Low Price,High Price,...,Color,Environment,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode
0,PUMPKINS,BALTIMORE,NaN,24 inch bins,NaN,NaN,NaN,04/29/2017,270,280.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E,NaN
1,PUMPKINS,BALTIMORE,NaN,24 inch bins,NaN,NaN,NaN,05/06/2017,270,280.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E,NaN
2,PUMPKINS,BALTIMORE,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,160,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
3,PUMPKINS,BALTIMORE,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,160,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
4,PUMPKINS,BALTIMORE,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,11/05/2016,90,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN

In [42]:
boston.head()

,Commodity Name,City Name,Type,Package,Variety,Sub Variety,Grade,Date,Low Price,High Price,...,Color,Environment,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode
0,PUMPKINS,BOSTON,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,160,200,...,ORANGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
1,PUMPKINS,BOSTON,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,160,200,...,ORANGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
2,PUMPKINS,BOSTON,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,160,200,...,ORANGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
3,PUMPKINS,BOSTON,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,160,200,...,ORANGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
4,PUMPKINS,BOSTON,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,160,180,...,ORANGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN

In [43]:
new_york.head()

,Commodity Name,City Name,Type,Package,Variety,Sub Variety,Grade,Date,Low Price,High Price,...,Color,Environment,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode
0,PUMPKINS,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,150,170,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
1,PUMPKINS,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,150,170,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
2,PUMPKINS,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,130,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
3,PUMPKINS,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,130,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
4,PUMPKINS,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,120,140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN

In [44]:
philadelphia.head()

,Commodity Name,City Name,Type,Package,Variety,Sub Variety,Grade,Date,Low Price,High Price,...,Color,Environment,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode
0,PUMPKINS,PHILADELPHIA,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,09/16/2017,140,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
1,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,150,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
2,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,150,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
3,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,150,160,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
4,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,10/01/2016,140,140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN

## Clean Your Data

In the last lesson, we cleaned the data related to San Francisco. Pull up your notebook from the last lesson and use it as a reference to clean up these new dataframes.

In [53]:
# Clean your data here!

def clean_city(df):
    df = df.copy()
   
    df = df.rename(columns={
        "Variety": "variety",
        "Date": "date",
        "Low Price": "low_price",
        "High Price": "high_price",
        "Origin": "origin"
    })
 
    df["date"] = pd.to_datetime(df["date"], errors="coerce")
    df["low_price"] = pd.to_numeric(df["low_price"], errors="coerce")
    df["high_price"] = pd.to_numeric(df["high_price"], errors="coerce")
    
    df["avg_price"] = (df["low_price"] + df["high_price"]) / 2
    
    df = df.dropna(subset=["low_price", "high_price"], how="all")
    
    return df

baltimore = clean_city(baltimore)
boston = clean_city(boston)
new_york = clean_city(new_york)
philadelphia = clean_city(philadelphia)

baltimore.head()

,Commodity Name,City Name,Type,Package,variety,Sub Variety,Grade,date,low_price,high_price,...,Environment,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode,avg_price
0,PUMPKINS,BALTIMORE,NaN,24 inch bins,NaN,NaN,NaN,2017-04-29,270,280.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E,NaN,275.0
1,PUMPKINS,BALTIMORE,NaN,24 inch bins,NaN,NaN,NaN,2017-05-06,270,280.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E,NaN,275.0
2,PUMPKINS,BALTIMORE,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,2016-09-24,160,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,160.0
3,PUMPKINS,BALTIMORE,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,2016-09-24,160,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,160.0
4,PUMPKINS,BALTIMORE,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,2016-11-05,90,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,95.0

In [54]:
boston.head()

,Commodity Name,City Name,Type,Package,variety,Sub Variety,Grade,date,low_price,high_price,...,Environment,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode,avg_price
0,PUMPKINS,BOSTON,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,2016-09-24,160,200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,180.0
1,PUMPKINS,BOSTON,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,2016-09-24,160,200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,180.0
2,PUMPKINS,BOSTON,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,2016-09-24,160,200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,180.0
3,PUMPKINS,BOSTON,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,2016-09-24,160,200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,180.0
4,PUMPKINS,BOSTON,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,2016-09-24,160,180,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,170.0

In [55]:
new_york.head()

,Commodity Name,City Name,Type,Package,variety,Sub Variety,Grade,date,low_price,high_price,...,Environment,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode,avg_price
0,PUMPKINS,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,2016-09-24,150,170,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,160.0
1,PUMPKINS,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,2016-09-24,150,170,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,160.0
2,PUMPKINS,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,2016-09-24,130,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,140.0
3,PUMPKINS,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,2016-09-24,130,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,140.0
4,PUMPKINS,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,2016-09-24,120,140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,130.0

In [56]:
philadelphia.head()

,Commodity Name,City Name,Type,Package,variety,Sub Variety,Grade,date,low_price,high_price,...,Environment,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode,avg_price
0,PUMPKINS,PHILADELPHIA,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,2017-09-16,140,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,145.0
1,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,2016-09-24,150,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,150.0
2,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,2016-09-24,150,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,150.0
3,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,2016-09-24,150,160,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,155.0
4,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,2016-10-01,140,140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,140.0

## Combine Your Data

Now that you have four clean sets of data, combine all four into one dataframe that represents the entire Northeast region.

In [58]:
# Combine the four dataframes into one!

northeast = pd.concat([baltimore, boston, new_york, philadelphia], ignore_index=True)

## Answer Some Questions

Use `groupby()` and `agg()` to answer the following two questions:

1. What is the mean low and high prices for each type of **unit of sale** in the Northeast region? 
2. For each region, what is the average number of pumpkins per variety that came into terminal markets for the year?

In [ ]:
# Put your code here to find the mean low and high prices in the Northeast region for each type of unit of sale.

northeast.groupby("Unit of Sale").agg({
    "low_price": "mean",
    "high_price": "mean"
})

               low_price  high_price
Unit of Sale
EACH           47.916667   59.166667
PER BIN       185.845070  206.619718
SHELLACKED     16.000000   17.545455

In [60]:
# Put your code here to find the average number of pumpkins coming into terminal markets of each variety.

northeast.groupby("variety")["avg_price"].mean()

variety
BIG MACK TYPE               138.363636
BLUE TYPE                   272.500000
CINDERELLA                  213.512821
FAIRYTALE                   206.445946
HOWDEN TYPE                 164.966518
HOWDEN WHITE TYPE           175.000000
KNUCKLE HEAD                249.722222
MINIATURE                    17.139175
MIXED HEIRLOOM VARIETIES    220.000000
PIE TYPE                    140.761364
Name: avg_price, dtype: float64

In [62]:
import os
os.getcwd()

'c:\\Users\\peele\\OneDrive\\LaunchCode\\data-analysis-projects\\data-manipulation\\studio\\data-manipulation-studio'

## Bonus Mission

Try answering the same questions for the Midwest (Chicago, Detroit, and St. Louis) or the Southeast (Atlanta, Columbia, and Miami) regions.

In [59]:
# Try the bonus mission if you have time!