# Exploratory Data Analysis with pandas Studio

## Data Analysis of IMDB movies data

#### Blocks have been created for your code

#### Click on the following link and download the dataset from [Kaggle](https://www.kaggle.com/PromptCloudHQ/imdb-data).

### 1. Read data

In [1]:
import pandas as pd

print("Pandas version:", pd.__version__)

Pandas version: 2.3.3

In [2]:
# import pandas
import pandas as pd

# create your data variabe using .read_csv 
data = pd.read_csv("IMDB-Movie-Data.csv")


# create your data_indexed variable here
data_indexed = data.set_index("Title")

In [9]:
import pandas as pd

# If you are having trouble reading your file, try finding the path.
data = pd.read_csv("IMDB-Movie-Data.csv")

# Right click on your data set, on the pop-up menu select "Copy Path" then paste it into your read_csv() function.
data_indexed = data.set_index("Title")

data_indexed.head()

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [8]:
import pandas as pd


# Read data with specified explicit index
data_indexed = pd.read_csv("IMDB-Movie-Data.csv", index_col="Title")


#print(data_indexed)
print(data_indexed)

                         Rank                     Genre  \
Title
Guardians of the Galaxy     1   Action,Adventure,Sci-Fi
Prometheus                  2  Adventure,Mystery,Sci-Fi
Split                       3           Horror,Thriller
Sing                        4   Animation,Comedy,Family
Suicide Squad               5  Action,Adventure,Fantasy
...                       ...                       ...
Secret in Their Eyes      996       Crime,Drama,Mystery
Hostel: Part II           997                    Horror
Step Up 2: The Streets    998       Drama,Music,Romance
Search Party              999          Adventure,Comedy
Nine Lives               1000     Comedy,Family,Fantasy

                                                               Description  \
Title
Guardians of the Galaxy  A group of intergalactic criminals are forced ...
Prometheus               Following clues to the origin of mankind, a te...
Split                    Three girls are kidnapped by a man with a diag...
Sing                     In a city of humanoid animals, a hustling thea...
Suicide Squad            A secret government agency recruits some of th...
...                                                                    ...
Secret in Their Eyes     A tight-knit team of rising investigators, alo...
Hostel: Part II          Three American college students studying abroa...
Step Up 2: The Streets   Romantic sparks occur between two dance studen...
Search Party             A pair of friends embark on a mission to reuni...
Nine Lives               A stuffy businessman finds himself trapped ins...

                                     Director  \
Title
Guardians of the Galaxy            James Gunn
Prometheus                       Ridley Scott
Split                      M. Night Shyamalan
Sing                     Christophe Lourdelet
Suicide Squad                      David Ayer
...                                       ...
Secret in Their Eyes                Billy Ray
Hostel: Part II                      Eli Roth
Step Up 2: The Streets             Jon M. Chu
Search Party                   Scot Armstrong
Nine Lives                   Barry Sonnenfeld

                                                                    Actors  \
Title
Guardians of the Galaxy  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...
Prometheus               Noomi Rapace, Logan Marshall-Green, Michael Fa...
Split                    James McAvoy, Anya Taylor-Joy, Haley Lu Richar...
Sing                     Matthew McConaughey,Reese Witherspoon, Seth Ma...
Suicide Squad            Will Smith, Jared Leto, Margot Robbie, Viola D...
...                                                                    ...
Secret in Their Eyes     Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...
Hostel: Part II          Lauren German, Heather Matarazzo, Bijou Philli...
Step Up 2: The Streets   Robert Hoffman, Briana Evigan, Cassie Ventura,...
Search Party             Adam Pally, T.J. Miller, Thomas Middleditch,Sh...
Nine Lives               Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...

                         Year  Runtime (Minutes)  Rating   Votes  \
Title
Guardians of the Galaxy  2014                121     8.1  757074
Prometheus               2012                124     7.0  485820
Split                    2016                117     7.3  157606
Sing                     2016                108     7.2   60545
Suicide Squad            2016                123     6.2  393727
...                       ...                ...     ...     ...
Secret in Their Eyes     2015                111     6.2   27585
Hostel: Part II          2007                 94     5.5   73152
Step Up 2: The Streets   2008                 98     6.2   70699
Search Party             2014                 93     5.6    4881
Nine Lives               2016                 87     5.3   12435

                         Revenue (Millions)  Metascore
Title
Guardians of the Galaxy              333.13       76.0
Prometheus                           126.46       65.0
Split                                138.12       62.0
Sing                                 270.32       59.0
Suicide Squad                        325.02       40.0
...                                     ...        ...
Secret in Their Eyes                    NaN       45.0
Hostel: Part II                       17.54       46.0
Step Up 2: The Streets                58.01       50.0
Search Party                            NaN       22.0
Nine Lives                            19.64       11.0

[1000 rows x 11 columns]

### 2. View Data
#### As we go through this section, write your own definitions of what each function does as a comment in the code box.

In [ ]:
# Use the head() function to view the first 5 rows of the data set

data.head()

#This function gives me a preview of the dataset to make sure its the correct one

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [ ]:
# Use the tail() function to view the last 5 rows of the data set

data.tail()

#If I want to see how my dataset ends and make sure nothing is left out, I would use this function

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

### 3. Understand basic information about the data
#### As we go through this section, write your own definitions of what each function does as a comment in the code box.

In [ ]:
# The info() function: 

data.info()

#This function shows me an entire dataframe. Like the amount of rows and columns, column name, data type for each column etc

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Title               1000 non-null   object
 2   Genre               1000 non-null   object
 3   Description         1000 non-null   object
 4   Director            1000 non-null   object
 5   Actors              1000 non-null   object
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64
 10  Revenue (Millions)  872 non-null    float64
 11  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 93.9+ KB

In [ ]:
# shape:

  #This attribute tells me the size my dataframe  

# what information does shape provide?  what is the order?

  #It gives me a pair of numbers in the order of: # of rows & # of columns.


data.shape

(1000, 12)

In [15]:
# columns:

  #This attribute lists all the column names in my dataframe

# what information does columns provide?

  #It lets me know what data is available and what is column is.

data.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [16]:
# The describe() function: 

  #This function gives me a summary of the numerical columns like: count, mean, standard deviation, min, max etc

data.describe

<bound method NDFrame.describe of      Rank                    Title                     Genre  \
0       1  Guardians of the Galaxy   Action,Adventure,Sci-Fi
1       2               Prometheus  Adventure,Mystery,Sci-Fi
2       3                    Split           Horror,Thriller
3       4                     Sing   Animation,Comedy,Family
4       5            Suicide Squad  Action,Adventure,Fantasy
..    ...                      ...                       ...
995   996     Secret in Their Eyes       Crime,Drama,Mystery
996   997          Hostel: Part II                    Horror
997   998   Step Up 2: The Streets       Drama,Music,Romance
998   999             Search Party          Adventure,Comedy
999  1000               Nine Lives     Comedy,Family,Fantasy

                                           Description              Director  \
0    A group of intergalactic criminals are forced ...            James Gunn
1    Following clues to the origin of mankind, a te...          Ridley Scott
2    Three girls are kidnapped by a man with a diag...    M. Night Shyamalan
3    In a city of humanoid animals, a hustling thea...  Christophe Lourdelet
4    A secret government agency recruits some of th...            David Ayer
..                                                 ...                   ...
995  A tight-knit team of rising investigators, alo...             Billy Ray
996  Three American college students studying abroa...              Eli Roth
997  Romantic sparks occur between two dance studen...            Jon M. Chu
998  A pair of friends embark on a mission to reuni...        Scot Armstrong
999  A stuffy businessman finds himself trapped ins...      Barry Sonnenfeld

                                                Actors  Year  \
0    Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014
1    Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012
2    James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016
3    Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016
4    Will Smith, Jared Leto, Margot Robbie, Viola D...  2016
..                                                 ...   ...
995  Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...  2015
996  Lauren German, Heather Matarazzo, Bijou Philli...  2007
997  Robert Hoffman, Briana Evigan, Cassie Ventura,...  2008
998  Adam Pally, T.J. Miller, Thomas Middleditch,Sh...  2014
999  Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...  2016

     Runtime (Minutes)  Rating   Votes  Revenue (Millions)  Metascore
0                  121     8.1  757074              333.13       76.0
1                  124     7.0  485820              126.46       65.0
2                  117     7.3  157606              138.12       62.0
3                  108     7.2   60545              270.32       59.0
4                  123     6.2  393727              325.02       40.0
..                 ...     ...     ...                 ...        ...
995                111     6.2   27585                 NaN       45.0
996                 94     5.5   73152               17.54       46.0
997                 98     6.2   70699               58.01       50.0
998                 93     5.6    4881                 NaN       22.0
999                 87     5.3   12435               19.64       11.0

[1000 rows x 12 columns]>

### 4. Data Selection -- Indexing and Slicing

In [17]:
#  Extract data as series
# define and print the variable 'genre'

genre = data["Genre"]
print(genre)

0       Action,Adventure,Sci-Fi
1      Adventure,Mystery,Sci-Fi
2               Horror,Thriller
3       Animation,Comedy,Family
4      Action,Adventure,Fantasy
                 ...
995         Crime,Drama,Mystery
996                      Horror
997         Drama,Music,Romance
998            Adventure,Comedy
999       Comedy,Family,Fantasy
Name: Genre, Length: 1000, dtype: object

In [18]:
# Extract the data as a dataframe and print it

genre_df = data[["Genre"]]
print(genre_df)

                        Genre
0     Action,Adventure,Sci-Fi
1    Adventure,Mystery,Sci-Fi
2             Horror,Thriller
3     Animation,Comedy,Family
4    Action,Adventure,Fantasy
..                        ...
995       Crime,Drama,Mystery
996                    Horror
997       Drama,Music,Romance
998          Adventure,Comedy
999     Comedy,Family,Fantasy

[1000 rows x 1 columns]

In [19]:
# Extract data using rows

# loc function

data_indexed.loc[["Guardians of the Galaxy", "Prometheus", "Sing"]]

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0

In [20]:
# iloc function

data.iloc[0:3]

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0

### 5. Data Selection - Based on Conditional Filtering

In [21]:
# Use the code block to select movies that have been released between 2010-2016, with a rating of less than 6.0, but generated a signifianct (top) revenue.

# Movies released between 2010–2016, rating < 6.0, and top revenue

filtered = data[
    (data["Year"] >= 2010) &
    (data["Year"] <= 2016) &
    (data["Rating"] < 6.0)
]

top_results = filtered.sort_values(by="Revenue (Millions)", ascending=False)

top_results.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
941,942,The Twilight Saga: Eclipse,"Adventure,Drama,Fantasy",As a string of mysterious killings grips Seatt...,David Slade,"Kristen Stewart, Robert Pattinson, Taylor Laut...",2010,124,4.9,192740,300.52,58.0
366,367,The Twilight Saga: Breaking Dawn - Part 2,"Adventure,Drama,Fantasy","After the birth of Renesmee, the Cullens gathe...",Bill Condon,"Kristen Stewart, Robert Pattinson, Taylor Laut...",2012,115,5.5,194329,292.30,52.0
925,926,The Twilight Saga: Breaking Dawn - Part 1,"Adventure,Drama,Fantasy",The Quileutes close in on expecting parents Ed...,Bill Condon,"Kristen Stewart, Robert Pattinson, Taylor Laut...",2011,117,4.9,190244,281.28,45.0
126,127,Transformers: Age of Extinction,"Action,Adventure,Sci-Fi",Autobots must escape sight from a bounty hunte...,Michael Bay,"Mark Wahlberg, Nicola Peltz, Jack Reynor, Stan...",2014,165,5.7,255483,245.43,32.0
657,658,Teenage Mutant Ninja Turtles,"Action,Adventure,Comedy","When a kingpin threatens New York City, a grou...",Jonathan Liebesman,"Megan Fox, Will Arnett, William Fichtner, Noel...",2014,101,5.9,178527,190.87,31.0

In [ ]:
# Note: The article is expecting more than 1 Twilight movie at the time of publishing.  
#To find the second Twilight movie, try manipulating the quantile value.  
#How specific can you get?

fine_quantiles = [
    0.99, 0.98, 0.97, 0.965, 0.96, 
    0.955, 0.95, 0.945, 0.94
]

for q in fine_quantiles:
    cutoff = base["Revenue (Millions)"].quantile(q)
    top_rev = base[base["Revenue (Millions)"] >= cutoff]
    twilight_count = top_rev["Title"].str.contains("Twilight", case=False, na=False).sum()
    print(q, "cutoff =", round(cutoff, 2), "Twilight movies found =", twilight_count)


    #I was able to get as specific as .99 quantile and find 2 Twilight movies that are above the  threshold.

0.99 cutoff = 291.42 Twilight movies found = 2
0.98 cutoff = 275.54 Twilight movies found = 3
0.97 cutoff = 232.34 Twilight movies found = 3
0.965 cutoff = 202.87 Twilight movies found = 3
0.96 cutoff = 182.96 Twilight movies found = 3
0.955 cutoff = 169.61 Twilight movies found = 3
0.95 cutoff = 164.97 Twilight movies found = 3
0.945 cutoff = 163.37 Twilight movies found = 3
0.94 cutoff = 149.02 Twilight movies found = 3